### ISSUE TITLE
[FEATURE] Update the EAP Testing API for Release 2

### ISSUE THREAD

**Issue by glennb-mitre** [glennb-mitre/Spectrum-Access_System-Release-2#1]
### Description
Update the Release 1 "API" to support Release 2 test cases.

### Problem Statement
Rel 2 enhanced antenna pattern is not implemented. We need to implement it using rel 1 antenna.py file as reference.

### Requirements
Requirements detailed in Annex 5.2.1 of referenced TS-1001.

- Table 2. Necessity of enhanced antenna pattern information in each method, implement:
    - B1, C, D, E
    - Method F is implemented in referenced R1 API (antenna.py)
- Algorithm definitions provided in section 5.2.1.

Note: Method A is included for completeness and has not been implemented.

### Files
TS-1001 v1.4.1-r5.0 (towards 1.5.0)
[antenna.py](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/tree/master/src/harness/reference_models/antenna)

### Tasks
Include specific tasks in the order they need to be done in.

- [x] Refactor existing code
- [x] Review Method F in Antenna.py
- [ ] Develop test case for Method F
- [ ] Develop test cases for Methods B1, C, D, E
- [x] Implement method B1, C, D, E
- [x] Add code for method F form Rel 1
- [x] Implement code for importing antenna pattern database
- [x] Implement code for selecting methods based on inputs

**Comment by glennb-mitre** [comment]
Nick is refactoring functions and variables.
A Class structure is not needed.

**Comment by nicks-mitre** [comment]
Nearly finished refactoring. Pylint now gives 2 warnings (unused arguments "ant_azimuth" and "ant_mech_downtilt" in the "get_given_2d_pattern_gains" function) and 10 refactors (various "Too many <X>," where <X> is "local variables," "arguments," or "statements." 
The get_given_2d_pattern_gains function has been giving me the most trouble because it has 45 (previously more) of a maximum allowed 15 local variables (from the PEP-8 standard, with which I personally disagree). I've had difficulty parsing the function, partly due to its complexity, but also because many of the variables seem to have legitimate reasons for existing. I just thought of a way to further refactor/reduce the number of variables in the function, and I will implement it soon, but it may be more helpful to break the function into subfunctions.

At this point, I have also created several helper functions to help de-duplicate and parameterize commonly used portions of code.

**Comment by nicks-mitre** [comment]
I broke out part of the get_given_2d_pattern_gains function that was repeated with slight variations into a subfunction, _get_gain_at_angle. This resolved the "too many local variables" Pylint refactor. I then used a debugger to verify that the types and values of the variables used and returned by the refactored version of get_given_2d_pattern_gains match those of the un-refactored version (from commit 2551ad0).

**Comment by raina226** [comment]
Implemented method B1,C,D,E and F(from Rel 1). Also added code for importing antenna database and selecting methods based on inputs provided. Code is partially complete and needs to be reviewed.
