### ISSUE TITLE
[FEATURE] Develop Spectrum Access System Reference Implementation

### ISSUE THREAD

**Issue by glennb-mitre** [glennb-mitre/Spectrum-Access_System-Release-2#11]
### Description
Create a Spectrum Access System (SAS) Release 1 Reference Implementation (RI). The SAS-R1 RI will be used as a foundation for a future SAS-R2 Reference Implementation.

### Problem Statement
While the [SAS 1 Test Harness](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/tree/fake_sas_python3/src/harness) provides "[fake_sas.py](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/fake_sas_python3/src/harness/fake_sas.py)," which implements some portions of a sample SAS Server against which the tests are run, large swaths of the SAS Protocol were left unimplemented, and the parts that were implemented performed little to no SAS-related calculations. Instead, fake_sas largely returns a success response for most of the methods it implements without checking if a successful response would be appropriate.

### Requirements
The protocols and data objects are described in the following documents:

1. WINNF-TS-0016-V1.2.7 SAS to CBSD Technical Specification
2. WINNF-SSC-0002 v10.0.0 Signaling Protocols and Procedures for Citizens Broadband Radio Service (CBRS): WInnForum Recognized CBRS Air Interfaces and Measurements. (Referenced by [1]). 
3. WINNF-TS-0096-V1.4.0 Signaling Protocols and Procedures for Citizens Broadband Radio Service (CBRS): Spectrum Access System (SAS) - SAS Interface Technical Specification
4. WINNF-TS-0245-V1.2.0 Operations for Citizens Broadband Radio Service (CBRS): Priority Access License (PAL) Database
    Technical Specification
The latest versions of the above specifications can be found [here](https://cbrs.wirelessinnovation.org/release-1-standards-specifications) and [here](https://cbrs.wirelessinnovation.org/policies-and-procedures).

### Files
(See the 'nick-ri' branch)

### Tasks
Include specific tasks in the order they need to be done in.
- [x] Implement object types according to the specification and enforce input validation.
- [ ] Create a well-formed reference_sas module based on the existing annotated versions of fake_sas.py and sas_interface.py with documentation and using the object types implemented in the previous task for type annotation and message creation/validation. After completing this task, the SAS-SAS or SAS-CBSD protocol's methods each have a method outline (empty body) with correct parameters, type annotations, and a helpful docstring.
- [ ] Determine and document the logic required for each SAS-SAS and CBSD-SAS method. For example, when a Grant Request should be approved and when a Grant Request should be denied.
- [ ] Implement the logic documented in the previous task.
- [ ] Use a sample CBSD to test the implementation.

Building the SAS R2 RI using this code as a foundation should be tracked as a separate issue.
