### ISSUE TITLE
[FEATURE] Certificate Checker Script Development

### ISSUE THREAD

**Issue by glennb-mitre** [glennb-mitre/Spectrum-Access_System-Release-2#6]
### Description
A bash script to validate SAS-1 certificate integrity, used by fake-sas and test cases.

### Problem Statement
Certificate issues are impacting test case development and execution.

### Requirements
- Check if the file exists.
- Check if the file is a cert file.
- Check if the cert file is corrupted.
- Check if the cert file is expired.
- Check if the cert file or its ca file is in the system ca-bundle.

### Files
- cert-check.sh

### Tasks
Include specific tasks in the order they need to be done in.
- [x] Identify cert verification requirements
- [x] Develop and test the verification workflow
- [x] Develop the cert-checker script
- [x] Test the script

**Comment by jordang-mitre** [comment]
I finished the initial script.
It can take a directory and verify that the files in it are pem files, non-expired, and whether or not they are in the system CA store.
Next steps will be to add command-line options and create tests.

**Comment by jordang-mitre** [comment]
I finished the test scripts.
