### ISSUE TITLE
[FEATURE] WINNF.FT.S.REL2.RI.EAP.1 Test Case Development

### ISSUE THREAD

**Issue by glennb-mitre** [glennb-mitre/Spectrum-Access_System-Release-2#8]
### Description
Test case WINNF.FT.S.REL2.RI.EAP.1 is for testing of antenna gain calculation using EAP methods.

### Requirements
Test data needs to be created as specified in the spec
### Files
A list of files or test code related to this issue.
TS-4006, pp. 23

### Tasks
- [x] Review spec for WINNF.FT.S.REL2.RI.EAP.1.
- [x] Write code
- [x] Create test data based on spec
- [x] Test code with the data created in Task 3

**Comment by glennb-mitre** [comment]
Created test data.
Reviewed test specification.

**Comment by raina226** [comment]
Partially implemented, code for antenna gain calculation using reference model is done, need to add code for comparing this with the value provided by the testing SAS . Code needs to be reviewed.
