### ISSUE TITLE
[FEATURE] WINNF.FT.S.REL2.RI.EAP.2 Test Case Development

### ISSUE THREAD

**Issue by glennb-mitre** [glennb-mitre/Spectrum-Access_System-Release-2#9]
Description
test case WINNF.FT.S.REL2.RI.EAP.2. is for testing the Enhanced Antenna Pattern for DPA Protection

Requirements
This test follows the same test procedure and pass/fail criteria as WINNF.FT.S.PPR.1 from release 1. So, code from release 1 should be reused as much as possible.

Files
TS-4006, pp. 24

##Tasks
- [x] Review spec for WINNF.FT.S.REL2.RI.EAP.2.
- [ ] Review code from WINNF.FT.S.PPR.1 and determine what modifications are needed.
- [ ] Write code
- [ ] Create test data based on spec
- [ ] Test code with data created in Task 4.
